import logging
from contextlib import asynccontextmanager

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(name)s] %(levelname)s %(message)s",
)

import pycountry
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from sqlalchemy import text
from sqlalchemy.orm import Session

from app.database import engine, Base, SessionLocal
from app.routers import auth, languages, lessons, progress, ai_chat, generation
from app.routers import vocabulary as vocabulary_router
from app.routers import daily_tasks as daily_tasks_router
from app.routers import placement_test as placement_test_router
from app.routers import ai_tools as ai_tools_router

# Import all models so they register with Base
from app.models import user, language, lesson, progress as progress_models, chat, generation as generation_models  # noqa: F811
from app.models import daily_task as daily_task_models  # noqa: F811
from app.models.user import PasswordResetToken  # noqa: F401 — registers table with Base
from app.models.language import Language
from app.models.progress import Achievement
from app.models.daily_task import DailyTaskTemplate
from app.utils.language_flags import infer_flag_for_language_code

logger = logging.getLogger("linguaai")


# ── Default achievements (gamification rules, not content) ─────────────
DEFAULT_ACHIEVEMENTS = [
    {"name": "First Steps", "description": "Complete your first lesson", "icon": "🎯", "condition_type": "lessons", "condition_value": 1},
    {"name": "Dedicated Learner", "description": "Complete 10 lessons", "icon": "📚", "condition_type": "lessons", "condition_value": 10},
    {"name": "Language Master", "description": "Complete 50 lessons", "icon": "🏆", "condition_type": "lessons", "condition_value": 50},
    {"name": "Quick Start", "description": "Earn your first 100 XP", "icon": "⚡", "condition_type": "xp", "condition_value": 100},
    {"name": "Rising Star", "description": "Earn 1,000 XP", "icon": "🌟", "condition_type": "xp", "condition_value": 1000},
    {"name": "XP Champion", "description": "Earn 5,000 XP", "icon": "💎", "condition_type": "xp", "condition_value": 5000},
    {"name": "Consistent", "description": "3-day streak", "icon": "🔥", "condition_type": "streak", "condition_value": 3},
    {"name": "Week Warrior", "description": "7-day streak", "icon": "💪", "condition_type": "streak", "condition_value": 7},
    {"name": "Monthly Master", "description": "30-day streak", "icon": "👑", "condition_type": "streak", "condition_value": 30},
    {"name": "Practice Makes Perfect", "description": "Complete 100 exercises", "icon": "✏️", "condition_type": "exercises", "condition_value": 100},
    {"name": "Exercise Machine", "description": "Complete 500 exercises", "icon": "🤖", "condition_type": "exercises", "condition_value": 500},
    {"name": "Unstoppable", "description": "Complete 1,000 exercises", "icon": "🚀", "condition_type": "exercises", "condition_value": 1000},
]


DEFAULT_DAILY_TASKS = [
    {
        "task_type": "complete_lessons",
        "title": "Пройди 2 уроки",
        "description": "Завершіть 2 уроки сьогодні",
        "icon": "📚",
        "target_count": 2,
        "xp_reward": 30,
    },
    {
        "task_type": "vocab_review",
        "title": "Повтори 5 слів",
        "description": "Відкрийте словник і повторіть 5 слів",
        "icon": "🔤",
        "target_count": 5,
        "xp_reward": 20,
    },
    {
        "task_type": "chat_messages",
        "title": "Надішли 3 повідомлення AI",
        "description": "Попрактикуйтесь із AI-тьютором",
        "icon": "💬",
        "target_count": 3,
        "xp_reward": 15,
    },
]


def _bootstrap(db: Session) -> None:
    """Populate languages (from pycountry) and achievements if tables are empty.
    All actual learning content (courses, lessons, exercises) is generated by AI."""

    # Languages — from pycountry ISO 639
    _BLOCKED_LANG_CODES = {"ru"}  # removed by project policy
    if db.query(Language).count() == 0:
        inserted = 0
        for lang in pycountry.languages:
            code = getattr(lang, "alpha_2", None)
            name = getattr(lang, "name", None)
            if not code or not name:
                continue
            code = str(code).lower()
            if code in _BLOCKED_LANG_CODES:
                continue
            db.add(Language(
                code=code,
                name=str(name),
                native_name=str(name),
                flag_emoji=infer_flag_for_language_code(code),
                description=f"Learn {name} with AI-generated adaptive lessons.",
            ))
            inserted += 1
        db.commit()
        logger.info("Bootstrapped %d languages from pycountry", inserted)

    updated_flags = 0
    for lang in db.query(Language).all():
        next_flag = infer_flag_for_language_code(lang.code)
        if next_flag != (lang.flag_emoji or ""):
            lang.flag_emoji = next_flag
            updated_flags += 1
    if updated_flags:
        db.commit()
        logger.info("Refreshed %d language flags", updated_flags)

    # Achievements — gamification rules
    if db.query(Achievement).count() == 0:
        for ach in DEFAULT_ACHIEVEMENTS:
            db.add(Achievement(**ach))
        db.commit()
        logger.info("Bootstrapped %d achievements", len(DEFAULT_ACHIEVEMENTS))

    # Daily task templates — seed once
    if db.query(DailyTaskTemplate).count() == 0:
        for task in DEFAULT_DAILY_TASKS:
            db.add(DailyTaskTemplate(**task))
        db.commit()
        logger.info("Bootstrapped %d daily task templates", len(DEFAULT_DAILY_TASKS))


@asynccontextmanager
async def lifespan(app: FastAPI):
    # Startup: create tables & bootstrap reference data
    Base.metadata.create_all(bind=engine)

    # Migrate: add columns that may not exist in already-created tables
    with engine.connect() as conn:
        conn.execute(text(
            "ALTER TABLE user_vocabulary "
            "ADD COLUMN IF NOT EXISTS last_reviewed_at TIMESTAMPTZ"
        ))
        conn.execute(text(
            "ALTER TABLE exercises "
            "ADD COLUMN IF NOT EXISTS hint TEXT NOT NULL DEFAULT ''"
        ))
        conn.execute(text(
            "ALTER TABLE exercises "
            "ADD COLUMN IF NOT EXISTS difficulty VARCHAR(20) NOT NULL DEFAULT 'medium'"
        ))
        conn.commit()

    db = SessionLocal()
    try:
        _bootstrap(db)
    finally:
        db.close()
    yield


app = FastAPI(
    title="LinguaAI API",
    description="Інтерактивна платформа для вивчення іноземних мов із АІ-агентом",
    version="2.0.0",
    lifespan=lifespan,
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:5173", "http://localhost:5174", "http://localhost:3000", "http://127.0.0.1:5173", "http://127.0.0.1:5174"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

app.include_router(auth.router)
app.include_router(languages.router)
app.include_router(lessons.router)
app.include_router(progress.router)
app.include_router(ai_chat.router)
app.include_router(generation.router)
app.include_router(vocabulary_router.router)
app.include_router(daily_tasks_router.router)
app.include_router(placement_test_router.router)
app.include_router(ai_tools_router.router)


@app.get("/")
def root():
    return {"message": "LinguaAI API v2.0", "docs": "/docs"}
